### ISSUE TITLE
Missing become: true when running install.sh

### ISSUE THREAD

**Issue by nsaleh** [leanbit/ansible-nvm#1]
Hi there, 

in https://github.com/leanbit/ansible-nvm/blob/master/tasks/main.yml#L18 
become_user is set but become:  true is missing so user is not changed resulting in an error when installing to non root ( or non ansible ) user.

adding become: true fixed this for me.

regards,
Nabil

**Comment by michelemina** [comment]
@nsaleh you're right. TKS
